### ISSUE TITLE
What is the purpose of this fork?

### ISSUE THREAD

**Issue by erikd** [evpobr/sndfile2k#9]

**Comment by evpobr** [comment]
1. Training for me how to create fork 😄 
2. Investigate of what how libsndfile would look like if all my ideas were merged to main repo (compiler visibility control and so on)
3. Some really experimental features are here, like doxygen documentation or stdio-based IO.

This is not intended to be public fork, like `libav` and `ffmpeg`. If i'll find something really useful, libsndfile will get it back.

**Comment by erikd** [comment]
Ok, you may want to specify that in the Readme.
